project:
  type: book
  output-dir: _book

book:
  title: "Nays2DHモデル技術解説書(DEMO版)"
  author: "RiverLink, Co., Ltd."
  date: "2025/4/22"
  chapters:
    - index.qmd
    - flow_equations.qmd
    - flow_roughness.qmd
    - sediment_equations.qmd
    - sediment_mixed.qmd
    - program_variables.qmd
    - program_subroutines.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

lang: ja 
