project:
  type: book
  output-dir: _book

book:
  title: "Nays2DHモデル技術解説書(暫定版)"
  author: "Kazutake Asahi"
  date: "2025/4/22"
  chapters:
    - index.qmd
    - part: "基礎式"
      chapters:
        - flow_equations.qmd
        - flow_roughness.qmd
        - sediment_equations.qmd
        - sediment_mixed.qmd
    - part: "プログラム説明"
      chapters:
        - program_variables.qmd
        - program_subroutines.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

lang: ja 
