name: Publish Quarto Book to GitHub Pages

on:
  push:
    branches: main  # mainブランチへのプッシュでトリガー

# 必要な権限を定義
permissions:
  contents: read
  pages: write
  id-token: write

# 一度に1つのデプロイメントのみを許可
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.3.450

      - name: Install dependencies
        run: |
          # ここに必要なパッケージのインストールを追加（必要な場合）
          # 例: sudo apt-get install -y ...

      - name: Render Quarto Book
        run: |
          cd doc
          quarto render --to html

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./doc/_book

  # GitHub Pagesへのデプロイジョブ
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 