name: Publish Book to GitHub Pages

on:
  push:
    branches: main  # mainブランチへのプッシュでトリガー
    # paths:
    #   - 'doc/_book/**'  # _bookディレクトリの変更があった場合のみ実行

# 必要な権限を定義
permissions:
  contents: read
  pages: write
  id-token: write

# 一度に1つのデプロイメントのみを許可
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Check for _book directory
        run: |
          if [ ! -d "./doc/_book" ]; then
            echo "警告: ./doc/_book ディレクトリが見つかりません。"
            echo "ローカルで 'cd doc && quarto render' を実行してから再度プッシュしてください。"
            exit 1
          fi
          echo "doc/_book ディレクトリが見つかりました。デプロイを続行します。"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./doc/_book

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3 