name: Publish Book to GitHub Pages

on:
  push:
    branches: main  # mainブランチへのプッシュでトリガー
    # paths:
    #   - 'doc/_book/**'  # _bookディレクトリの変更があった場合のみ実行

# 必要な権限を定義
permissions:
  contents: write  # gh-pagesブランチにプッシュするための権限

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 完全なGit履歴を取得

      - name: Debug Environment Info
        run: |
          echo "リポジトリ: $GITHUB_REPOSITORY"
          echo "ブランチ: $GITHUB_REF"
          echo "ワークスペース: $GITHUB_WORKSPACE"
          echo "現在のディレクトリ:"
          pwd
          echo "ディレクトリ内容:"
          ls -la
          echo "doc/_book内容:"
          ls -la ./doc/_book || echo "doc/_bookディレクトリが見つかりません"

      - name: Check for _book directory
        run: |
          if [ ! -d "./doc/_book" ]; then
            echo "警告: ./doc/_book ディレクトリが見つかりません。"
            echo "ローカルで 'cd doc && quarto render' を実行してから再度プッシュしてください。"
            exit 1
          fi
          echo "doc/_book ディレクトリが見つかりました。デプロイを続行します。"
          echo "ファイル一覧:"
          find ./doc/_book -type f | head -20

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./doc/_book  # デプロイするフォルダ
          branch: gh-pages     # デプロイ先のブランチ
          clean: true          # デプロイ先ブランチの古いファイルを削除
          token: ${{ secrets.GITHUB_TOKEN }}  # 明示的にトークンを指定
          git-config-name: GitHub Actions     # コミット時のユーザー名
          git-config-email: actions@github.com  # コミット時のメールアドレス
          commit-message: "Update documentation [skip ci]"

      - name: Output deployment results
        run: |
          echo "デプロイが完了しました"
          echo "GitHub Pagesを設定するには、リポジトリ設定（Settings > Pages）で:"
          echo "- Source: Deploy from a branch"
          echo "- Branch: gh-pages / (root)"
          echo "を選択してください" 