name: Publish Book to GitHub Pages

on:
  push:
    branches: main  # mainブランチへのプッシュでトリガー
    # paths:
    #   - 'doc/_book/**'  # _bookディレクトリの変更があった場合のみ実行

# 必要な権限を定義
permissions:
  contents: write  # gh-pagesブランチにプッシュするための権限

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for _book directory
        run: |
          if [ ! -d "./doc/_book" ]; then
            echo "警告: ./doc/_book ディレクトリが見つかりません。"
            echo "ローカルで 'cd doc && quarto render' を実行してから再度プッシュしてください。"
            exit 1
          fi
          echo "doc/_book ディレクトリが見つかりました。デプロイを続行します。"
          ls -la ./doc/_book

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./doc/_book  # デプロイするフォルダ
          branch: gh-pages     # デプロイ先のブランチ
          clean: true          # デプロイ先ブランチの古いファイルを削除 